import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout/Layout'
import Section from '../components/Section/Section'
import Button from '../components/Button/Button'
import alumni from './alumni.jpg'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Section>
          <main className={styles.banner}>
            <h1 className={styles.display}>Telkom University</h1>
            <p className={styles.text}>Sinergi Bangun Negeri</p>
            <Button>Lets Explore Telkom</Button>
          </main>
        </Section>
        <Section>
          <main className={styles.profile}>
              <h1 className={styles.title}>Profil Telkom University</h1>
              <p className={styles.text}>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia architecto tenetur asperiores corporis similique, ducimus, doloremque hic animi expedita nostrum, illo exercitationem ullam possimus? Ullam dolorum ipsum sapiente aspernatur eos exercitationem pariatur, voluptatibus a, quisquam quia necessitatibus temporibus obcaecati ut.
              </p>
          </main>
        </Section>
        <Section>
          <main className={styles.data_mahasiswa}>
              <div className={styles.students}>
                <h1 className={styles.title}>Profil Telkom University</h1>
                <p className={styles.text}>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia architecto tenetur asperiores corporis similique, ducimus, doloremque hic animi expedita nostrum, illo exercitationem ullam possimus? Ullam dolorum ipsum sapiente aspernatur eos exercitationem pariatur, voluptatibus a, quisquam quia necessitatibus temporibus obcaecati ut.
                </p>
              </div>
              <Image src={alumni} width={400} height={300}/>
          </main>
        </Section>
      </Layout>
    </div>
  )
}
