import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout/Layout'
import Section from '../components/Section/Section'
import Button from '../components/Button/Button'
import alumni from './alumni.jpg'
import Card from '../components/Card/Card'
import {mahasiswa} from '../data/mahasiswa'
import { useEffect, useState } from 'react'

export default function Home() {
  const[mhs, setMhs] =useState([])

  const fetchMahasiswa = async () => {
    try{
        const response = await fetch('/api/mahasiswas');
        const data = await response.json();
        setMhs(data) 
    }catch(err){
        console.error('Error' + err);
    }
};

  useEffect(()=>{
    fetchMahasiswa()
  })

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Section>
          <main className={styles.banner}>
            <h1 className={styles.display}>Telkom University</h1>
            <p className={styles.text}>Sinergi Bangun Negeri</p>
            <Button>Lets Explore Telkom</Button>
          </main>
        </Section>
        <Section>
          <main className={styles.profile}>
              <h1 className={styles.title}>Profil Telkom University</h1>
              <p className={styles.text}>
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia architecto tenetur asperiores corporis similique, ducimus, doloremque hic animi expedita nostrum, illo exercitationem ullam possimus? Ullam dolorum ipsum sapiente aspernatur eos exercitationem pariatur, voluptatibus a, quisquam quia necessitatibus temporibus obcaecati ut.
              </p>
          </main>
        </Section>
        <Section>
          <main className={styles.data_mahasiswa}>
              <div className={styles.students}>
                <h1 className={styles.title}>Profil Alumni Telkom University</h1>
                <p className={styles.text}>
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quia architecto tenetur asperiores corporis similique, ducimus, doloremque hic animi expedita nostrum, illo exercitationem ullam possimus? Ullam dolorum ipsum sapiente aspernatur eos exercitationem pariatur, voluptatibus a, quisquam quia necessitatibus temporibus obcaecati ut.
                </p>
              </div>
              <Image src={alumni} width={400} height={300}/>
          </main>
        </Section>
        <Section>
          <main className={styles.data_mahasiswa_aktif}>
              <h1 className={styles.title_section}>Data Mahasiswa</h1>
              <div className={styles.student_lists}>
                {
                  mhs.length != 0 && mhs.map(m => {
                    return <Card key={m.id} id={m.id} image={m.image} location={m.location} name={m.name} jurusan={m.jurusan}/>
                  })

                }
              </div>
          </main>
        </Section>
      </Layout>
    </div>
  )
}
