import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout/Layout'
import Section from '../components/Section/Section'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>
          <Section>
            Hi nama Saya Maulana Akbar Ramdhanasdds
          </Section>
        </Layout>
      </main>

      <footer>
      </footer>
    </div>
  )
}
